# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bert_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/bert_server.proto\x12\x04main\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t2H\n\x0e\x42\x65rtClassifier\x12\x36\n\x07Predict\x12\x14.main.PredictRequest\x1a\x15.main.PredictResponseB\x16Z\x14testBertClient/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bert_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024testBertClient/proto'
  _globals['_PREDICTREQUEST']._serialized_start=33
  _globals['_PREDICTREQUEST']._serialized_end=63
  _globals['_PREDICTRESPONSE']._serialized_start=65
  _globals['_PREDICTRESPONSE']._serialized_end=102
  _globals['_BERTCLASSIFIER']._serialized_start=104
  _globals['_BERTCLASSIFIER']._serialized_end=176
# @@protoc_insertion_point(module_scope)
